.github/workflows/ci.yml

Not just those against main. This is useful when reviews are behind and we need to stack PRs.

Turn on CI for all pull requests

---

Main.lean
TensorLib/NumpyRepr.lean

This is needed because while we will generally mutate the data in place, we will need to write new headers, e.g. for the potentially changed shape and row/column ordering. Moreover, for tensors we create from scratch, we will not in general have bits representing the header.
Tested by round-tripping in the python repl.
Unit tests are forthcoming.

Add writing numpy tensors back to disk

---

.github/workflows/ci.yml
Main.lean
TensorLib/NumpyRepr.lean
Test/parse_test.py

Not sure how this passed in the previous commit.
- Ensure Python is installed before running lake
- Remove the hard-coded little-endian '< in the dtype encoding

Fix pytest failure

---

TensorLib/Basic.lean
TensorLib/Dtype.lean

Data types with byte order. A small file, so
we may want to merge this with other files in the
future.

Add Dtype.lean

---

TensorLib/Basic.lean
TensorLib/Common.lean
TensorLib/Npy.lean

NumPy uses a custom binary format to store ndarrays. This file implements that format.

Npy file support

---

TensorLib/Basic.lean
TensorLib/Common.lean
TensorLib/Npy.lean
TensorLib/Tensor.lean

Add Tensor type

---

TensorLib/Basic.lean
TensorLib/Index.lean

"Basic" indexing means indexing with a constant or slice on all the dimensions. (Advanced indexing is for things like indexing by other arrays).
https://numpy.org/doc/stable/user/basics.indexing.html

Basic indexing

---

TensorLib/Broadcast.lean
TensorLib/Common.lean
TensorLib/Dtype.lean
TensorLib/Index.lean
TensorLib/Tensor.lean

We implement a common version of advanced indexing, where all arguments are (broadcastable to) int arrays.

Advanced indexing

---

TensorLib/Common.lean
TensorLib/Dtype.lean
TensorLib/Tensor.lean

Adds some conversions to and from signed int types

Bit hacking

---

TensorLib/Common.lean
TensorLib/Index.lean
TensorLib/Npy.lean
TensorLib/Slice.lean
TensorLib/Tensor.lean

Trivial cleanups

---

TensorLib/Basic.lean
TensorLib/Ufunc.lean

NumPy uses an abstraction of functions called [Ufunc](https://numpy.org/doc/2.1/reference/ufuncs.html). It has a lot of widgets in NumPy, but for now we just support lifting element-wise operations and broadcasting.

Universal functions

---

TensorLib/Index.lean
TensorLib/Tensor.lean
TensorLib/Ufunc.lean

The best-effort check we're doing to ensure an index is "compatible" with a shape is wrong headed. For example, if we're indexing a single element from an array, the output shape is [] but we're comparing it to the list of nat indices. Instead of trying to improve the notion, I just removed it and let the indexing itself fail if there's an incorrect index.

chore: Remove wrong index compatibility check

---

TensorLib/Dtype.lean
TensorLib/Npy.lean

There is no short term plan to have fp16 support in Lean. Let's remove for now. We have fp32 support in 4.16, so I'll implement that next. After that we won't have any TODO types.

chore: Remove float16

---

TensorLib/Common.lean
TensorLib/Dtype.lean

Float32 will be important for simulating KLR, as most floating point arithmetic on trainium is done at 32 bits.

feat: support Float32

---

TensorLib/Common.lean
TensorLib/Dtype.lean
TensorLib/Mgrid.lean
TensorLib/Tensor.lean

* Add some 1-liner utility methods
* Reorder some arguments based on `_root_` namespace. (e.g. writing `Int.foo` under `TensorLib` namespace is useless. You need to write it at root to be able to use prefix notation)
* Make some defs private
* marginally better debug messages
* Minor code movement

chore: noop tidying

---

TensorLib/Common.lean
TensorLib/Dtype.lean
TensorLib/Tensor.lean
TensorLib/Ufunc.lean

This rewrites some of the type casting/conversion code and adds NumPy's `astype` method. This is essential for most of the KLR kernels we want to evaluate, as (implicit) casting abounds. There are currently no implicit type conversions; we need to manually call `astype` for now.

feat: astype

---

TensorLib/Common.lean
TensorLib/Dtype.lean
TensorLib/Npy.lean
TensorLib/Tensor.lean
TensorLib/Test.lean

Endian-ness is a nice feature in NumPy; it's clear what the data should represent, it handles operations on arrays with different orderings, etc. But it's largely just an optimization. In our code, which is slow to begin with, we do not need this optimization. We remove considerable complexity by forcing all arrays in TensorLib to be little-endian.
One outcome of this is that we will save all .npy files as littleendian and rely on the Python programmer to convert if necessary.

chore: Make all arrays little-endian

---

TensorLib/Common.lean
TensorLib/Iterator.lean

Once we moved Shape to its own file, Common no longer depends on Iterator, so we can have a more straightfoward dependency graph now.

chore: tweak imports

---

TensorLib/Dtype.lean
TensorLib/Iterator.lean
TensorLib/Shape.lean
TensorLib/Tensor.lean

We need toNpy for npy-file IO
We had a bug that confused unit and non-unit strides. To keep that
from happening again, we remove the non-unit variant. It's easy
to recover by multiplying by the itemsize.

chore: make Tensor.toNpy public, remove non-unit strides

---

TensorLib/Common.lean
TensorLib/Test.lean

One IO #eval seems to be causing problems when used as a library in a different repo. As a matter of tidiness I replaced uses of #eval with #guard/example. I think keeping eval out of our code as a general rule is a good idea, as it tends to just dump output during builds. #guard/#guard_msgs is effective for local testing.

chore: Remove evals

---

TensorLib/Index.lean
TensorLib/Iterator.lean
TensorLib/Mgrid.lean
TensorLib/Ufunc.lean

There are two common pair iterator use cases
1. lock-step
2. carry-adder
This creates a scoped instance for (1) so you
can use `open scoped` to get the syntax we want
for lock-step iterators
for (i, j) in (iter1, iter2) do ...

chore: improve lock-step iterators

---

TensorLib/Basic.lean
TensorLib/Bytes.lean
TensorLib/Common.lean
TensorLib/Dtype.lean

We are refactoring Common to make more utilities useful from KLR and other importing projects. This will come in several steps for ease of code review and comments.
This is step 1: some conversions between IntX/UIntX and ByteArray. The goal is that we can import just the util functions we need for a given set of types, without getting lots of names we don't want.

chore: Refactor Common.lean I

---

TensorLib/Tensor.lean

This is a tiny patch that adds BEq to Tensor.
https://github.com/leanprover/KLR/pull/111 depends on this patch.

Add BEq to Tensor

---

TensorLib/Tensor.lean

This patch fixes intAtDimIndex to return the correct value at the location, by multiplying the size of element in dimIndexToPosition.
This makes the new `#guard` statements pass in this pull request.

Fix intAtDimIndex to return the right value

---

TensorLib/Bytes.lean
TensorLib/Tensor.lean

Adds a few missing functions for working with arrayscalar bools that are needed for https://github.com/leanprover/KLR/pull/222

feat: add missing functions for scalar bools
